name: "Unit Test Generator"
description: "Automatically generates unit tests for functions in the codebase"
inputs:
   robustai-api-key:
     required: true
     description: "Robust AI API Key"
   github-token:
     required: true
     description: "Github Actions token"
   repo-path:
     required: false
     default: './'
     description: "Path to the checked out repo to generate tests for"
runs:
  using: "composite"
  steps:
    - name: Check PR comment for trigger
      uses: khan/pull-request-comment-trigger@v1.1.0
      id: check
      with:
        trigger: "/gen_tests"
        reaction: rocket
      env:
        GITHUB_TOKEN: '${{ inputs.github-token }}'
    - name: Get PR branch
      uses: xt0rted/pull-request-comment-branch@v2
      id: comment-branch
    - name: Checkout PR Branch
      uses: actions/checkout@v3
      with:
        token: ${{ inputs.github-token }}
        ref: ${{ steps.comment-branch.outputs.head_ref }}
    - name: Fetch main branch
      shell: bash
      run: |
        git fetch origin main:main
      if: steps.check.outputs.triggered == 'true'
    - name: Download gen_tests install script
      shell: bash
      run: |
        cd ${GITHUB_ACTION_PATH}
        pip install -r requirements.txt
        python install.py
      env:
        ROBUSTAI_API_KEY: ${{ inputs.robustai-api-key }}
      if: steps.check.outputs.triggered == 'true'
    - name: Run gen_tests install script
      shell: bash
      run: |
        chmod +x ${GITHUB_ACTION_PATH}/install_script.sh
        ${GITHUB_ACTION_PATH}/install_script.sh
        rm ${GITHUB_ACTION_PATH}/install_script.sh
      if: steps.check.outputs.triggered == 'true'
    - name: Setup
      shell: bash
      run: |
        pip3 install --upgrade pip
        pip3 install --upgrade setuptools
        pip3 install ~/bin/robust_ai_utils.tar.gz
        echo "ROBUSTAI_API_KEY=${{ inputs.robustai-api-key }}" >> $GITHUB_ENV
      if: steps.check.outputs.triggered == 'true'
    - name: PWD
      shell: bash
      run: pwd
    - name: Run gen_tests
      id: run_gen_tests
      uses: 'selfagency/capture-output@v1'
      with:
        cmd: gen_tests
        args: --repo_path=${{ inputs.repo-path }},--mode=4,--run_debugging=False
      if: steps.check.outputs.triggered == 'true'
    - uses: stefanzweifel/git-auto-commit-action@v4
      name: Commit tests
      with:
          commit_user_name: "RobustAI"
          commit_message: "Generated unit tests"
          file_pattern: '**/*.py'
      if: steps.check.outputs.triggered == 'true'
    - uses: actions/github-script@v6
      with:
        script: |
          const OUTPUT_COMMENT = process.env.OUTPUT_COMMENT
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: OUTPUT_COMMENT
          })
      env:
        OUTPUT_COMMENT: ${{ steps.run_gen_tests.outputs.output }}
      if: steps.check.outputs.triggered == 'true'
      
branding:
  icon: 'cpu'
  color: green
