name: "Unit Test Generator"
description: "Automatically generates unit tests for functions in the codebase"
inputs:
   robustai-api-key:
     required: true
     description: "Robust AI API Key"
   github-token:
     required: true
     description: "Github Actions token"
   repo-path:
     required: false
     default: '.'
     description: "Path to the checked out repo to generate tests for"
   docker-run-args:
     required: false
     default: ""
     description: "Additional args to pass to docker run when running the gen_tests container"
   env-file-contents:
     required: false
     default: ""
     description: "Content of env file to be used when running generated tests"
runs:
  using: "composite"
  steps:
    - name: Check PR comment for trigger
      uses: khan/pull-request-comment-trigger@v1.1.0
      id: check
      with:
        trigger: "/gen_tests"
        reaction: rocket
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
    - name: Check PR comment for benchmark trigger
      uses: khan/pull-request-comment-trigger@v1.1.0
      id: check_benchmark
      with:
        trigger: "/benchmark_gen_tests"
        reaction: rocket
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
    - name: Checkout branch
      run: |
        if [ "${{ github.even_name }}" == "pull_request" ]; then
            PR_NUMBER="${{ github.event.number }}"
        else
            PR_NUMBER="${{ github.event.issue.number }}"
        fi
        echo $PR_NUMBER
        hub pr checkout $PR_NUMBER
      env:
        GITHUB_USER: ${{ github.repository_owner }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
      shell: bash
      if: steps.check.outputs.triggered == 'true' || steps.check_benchmark.outputs.triggered == 'true'
    - name: Comment link to action
      uses: mshick/add-pr-comment@v2
      with:
        message-id: ${{ github.run_id }}
        message: "⏳ Running test generation ([link](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}))"
      if: steps.check.outputs.triggered == 'true' || steps.check_benchmark.outputs.triggered == 'true'
    - name: Run Gen Tests
      uses: addnab/docker-run-action@v3
      with:
        registry: gcr.io
        image: revant/gen_tests:latest
        options: > 
          -v ${{ github.workspace }}:/app 
          -e ROBUSTAI_API_KEY=${{ inputs.robustai-api-key }}
          ${{ inputs.docker-run-args }}
        run: |
          cd ${{ inputs.repo-path }} &&
          git config --global --add safe.directory /app && git branch &&
          find . -name "requirement*" -type f -exec pip3 install -q -r '{}' ';' &&
          echo "${{ inputs.env-file-contents }}" > .env &&
          gen_tests --mode=4 --benchmark=${{ steps.check_benchmark.outputs.triggered }} > gen_tests_output.txt
      if: steps.check.outputs.triggered == 'true' || steps.check_benchmark.outputs.triggered == 'true'
    - name: Commit tests
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
          commit_user_name: "RobustAI"
          commit_message: "Generated unit tests"
          file_pattern: '*.py'
      if: steps.check.outputs.triggered == 'true' || steps.check_benchmark.outputs.triggered == 'true'
    - name: Add output PR comment
      id: gen_tests_output
      run: |
        echo "GEN_TESTS_OUTPUT<<EOF" >> "$GITHUB_ENV" &&
        cat ${{ inputs.repo-path }}/gen_tests_output.txt >> "$GITHUB_ENV" &&
        echo "EOF" >> "$GITHUB_ENV"
      shell: bash
      if: steps.check.outputs.triggered == 'true' || steps.check_benchmark.outputs.triggered == 'true'
    - name: Update comment with status
      uses: mshick/add-pr-comment@v2
      with:
        message-id: ${{ github.run_id }}
        update-only: true
        message: "✅ Test generation succeeded ([link](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}))"
        message-success: "✅ Test generation succeeded ([link](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}))"
        message-failure: "❌ Test generation failed ([link](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}))"
        message-cancelled: "❌ Test generation cancelled ([link](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}))"
      if: always()
    
branding:
  icon: 'cpu'
  color: green
